source "https://rubygems.org"

ruby ">= 3.2.0"

# Rails
gem "rails", "~> 7.2.0"

# Database
gem "pg", "~> 1.5"

# Web server
gem "puma", "~> 6.4"

# JSON serialization
gem "jsonapi-serializer", "~> 2.2"

# CORS
gem "rack-cors", "~> 2.0"

# Authentication
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.12"

# HTTP client for external APIs
gem "faraday", "~> 2.9"

# Background jobs (PostgreSQL-based, no Redis required)
gem "good_job", "~> 4.0"

# Performance
gem "bootsnap", require: false

# Timezone data for Windows
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.4"
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "bullet", "~> 7.2"
  gem "rubocop", "~> 1.68"
  gem "rubocop-rails", "~> 2.27"
  gem "rubocop-rspec", "~> 3.2"
end

group :test do
  gem "shoulda-matchers", "~> 6.4"
  gem "database_cleaner-active_record", "~> 2.2"
  gem "vcr", "~> 6.2"
  gem "webmock", "~> 3.23"
end
